CREATE TABLE pokemon (pokemon_id INTEGER AUTO_INCREMENT NOT NULL, name VARCHAR(255), color INTEGER, type INTEGER, PRIMARY KEY (pokemon_id))
CREATE TABLE color (color_id INTEGER AUTO_INCREMENT NOT NULL, color VARCHAR(255), PRIMARY KEY (color_id))
CREATE TABLE type (type_id INTEGER AUTO_INCREMENT NOT NULL, type VARCHAR(255), PRIMARY KEY (type_id))
ALTER TABLE pokemon ADD CONSTRAINT FK_pokemon_color FOREIGN KEY (color) REFERENCES color (color_id)
ALTER TABLE pokemon ADD CONSTRAINT FK_pokemon_type FOREIGN KEY (type) REFERENCES type (type_id)
INSERT INTO pokemon.color (color) VALUES ('BLACK')
INSERT INTO pokemon.color (color) VALUES ('RED')
INSERT INTO pokemon.color (color) VALUES ('GREEN')
INSERT INTO pokemon.color (color) VALUES ('YELLOW')
INSERT INTO pokemon.color (color) VALUES ('BLUE')
INSERT INTO pokemon.color (color) VALUES ('WHITE')
INSERT INTO pokemon.`type` (`type`) VALUES ('WARRIOR')
INSERT INTO pokemon.`type` (`type`) VALUES ('TEACHER')
INSERT INTO pokemon.`type` (`type`) VALUES ('SMALL')
INSERT INTO pokemon.`type` (`type`) VALUES ('BIG')
INSERT INTO pokemon.`type` (`type`) VALUES ('POET')
